### ISSUE TITLE
problem in class inheritance

### ISSUE THREAD

**Issue by astin2044327** [astin2044327/Infosys-project#1]
There has been some error flashing in class inheritance developed by developer

**Comment by bipeensinha** [comment]
Hi Ravi, Yes i am working on the code , you will get update , i am following this article  

[https://javascript.info/class-inheritance](url) 
![AZ400](https://user-images.githubusercontent.com/49720823/87890137-bcaffa80-ca52-11ea-87c3-6d79477c6d48.JPG)

**Comment by astin2044327** [comment]
thanks for the quick resolve.

**Comment by bipeensinha** [comment]
Thank you Ravi for all your help
